import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {initDemo,sampleReport} from './src/demo-report.js';
const elements=new Map();
const el=id=>{if(!elements.has(id))elements.set(id,{id,hidden:false,dataset:{},attrs:{},events:{},textContent:'',innerHTML:'',setAttribute(k,v){this.attrs[k]=v},addEventListener(k,f){this.events[k]=f},focus(){this.focused=true},scrollIntoView(){this.scrolled=true}});return elements.get(id)};
const tabs=['morning','evening','attention'].map(key=>{const e=el(key);e.dataset.advice=key;return e});
const doc={getElementById:id=>{assert.notEqual(id,'preview','sample must not read uploaded photo');return el(id)},querySelectorAll:()=>tabs};
let stops=0,exported;const progressStates=[];
globalThis.fetch=()=>{throw new Error('Demo must not call a remote analysis API')};
initDemo({stopCamera:()=>stops++,document:doc,download:data=>exported=data,progress:state=>progressStates.push(state),nextStep:async()=>{}});
await el('open-demo').events.click();
assert.deepEqual(progressStates.map(s=>s.percent),[0,25,50,75,100]);assert.equal(progressStates.at(-1).status,'done');assert.equal(el('open-demo').disabled,false);
assert.equal(stops,1);assert.equal(el('capture-section').hidden,true);assert.equal(el('demo-report').hidden,false);assert.equal(el('report-title').focused,true);
tabs[1].events.click();assert.match(el('advice-title').textContent,/基础护理/);assert.equal(tabs[1].attrs['aria-pressed'],'true');assert.equal(tabs[0].attrs['aria-pressed'],'false');
assert.equal((el('demo-highlights').innerHTML.match(/class="metric"/g)||[]).length,3);
assert.match(el('demo-highlights').innerHTML,/表面油光/);assert.match(el('demo-highlights').innerHTML,/纹理粗糙度/);
assert.equal((el('demo-dimensions').innerHTML.match(/class="metric"/g)||[]).length,8);
assert.equal(el('all-metrics').open,false);
el('view-advice').events.click();assert.equal(tabs[2].attrs['aria-pressed'],'true');assert.equal(el('advice-heading').focused,true);assert.equal(el('advice-heading').scrolled,true);
el('export-demo').events.click();assert.equal(exported.mode,'demo');assert.equal(exported.source,'fixed_sample');assert.equal(exported.usesUploadedPhoto,false);assert.match(exported.notice,/与上传照片无关/);assert.equal(exported.dimensions.length,8);
el('return-capture').events.click();assert.equal(el('capture-section').hidden,false);assert.equal(el('demo-report').hidden,true);assert.equal(el('open-demo').focused,true);
const html=await readFile('dist/assessment.html','utf8');
assert.match(html,/固定示例数据，与上传照片无关/);assert.match(html,/不消耗分析额度/);assert.match(html,/真实分析及按照片生成的建议，待接入分析服务后开放/);
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);
const demoSource=await readFile('src/demo-report.js','utf8');assert.doesNotMatch(demoSource,/fetch\s*\(|XMLHttpRequest|YOUCAM_API_KEY/);
const failingStates=[];const radarNode=el('radar-shape'),originalSet=radarNode.setAttribute;
radarNode.setAttribute=()=>{throw new Error('simulated render failure')};
initDemo({stopCamera:()=>{},document:doc,progress:s=>failingStates.push(s),nextStep:async()=>{}});
await el('open-demo').events.click();assert.equal(failingStates.at(-1).status,'error');assert.equal(failingStates.at(-1).percent,50);assert.equal(el('open-demo').disabled,false);assert.equal(el('demo-report').hidden,true);
radarNode.setAttribute=originalSet;await el('open-demo').events.click();assert.equal(failingStates.at(-1).status,'done');assert.equal(el('demo-report').hidden,false);
console.log('PASS: preparation progress, sample isolation, no analysis network calls, camera stop on report, advice switching, marked export, return focus, unique HTML IDs');
